<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="118383" started-at="2017-11-10T15:22:20Z" finished-at="2017-11-10T15:24:18Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="118383" started-at="2017-11-10T15:22:20Z" finished-at="2017-11-10T15:24:18Z">
      <class name="GroupTest.AppiumTut01.AppTestTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:GroupTest.AppiumTut01.AppTestTest@77caeb3e]" name="setUp" is-config="true" duration-ms="41741" started-at="2017-11-10T22:22:20Z" finished-at="2017-11-10T22:23:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="Login_TC01()[pri:0, instance:GroupTest.AppiumTut01.AppTestTest@77caeb3e]" name="Login_TC01" duration-ms="20010" started-at="2017-11-10T22:23:02Z" finished-at="2017-11-10T22:23:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_TC01 -->
        <test-method status="FAIL" signature="Login_TC03()[pri:0, instance:GroupTest.AppiumTut01.AppTestTest@77caeb3e]" name="Login_TC03" duration-ms="25858" started-at="2017-11-10T22:23:22Z" finished-at="2017-11-10T22:23:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Wrong Email or Password] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Wrong Email or Password] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at GroupTest.AppiumTut01.AppTestTest.Login_TC03(AppTestTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_TC03 -->
        <test-method status="PASS" signature="Login_TC02()[pri:0, instance:GroupTest.AppiumTut01.AppTestTest@77caeb3e]" name="Login_TC02" duration-ms="24688" started-at="2017-11-10T22:23:48Z" finished-at="2017-11-10T22:24:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_TC02 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:GroupTest.AppiumTut01.AppTestTest@77caeb3e]" name="tearDown" is-config="true" duration-ms="6006" started-at="2017-11-10T22:24:12Z" finished-at="2017-11-10T22:24:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- GroupTest.AppiumTut01.AppTestTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
